config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pages#home"

  resources :lists, only: [:new, :create, :edit, :update, :destroy] do
    resources :releases, only: [:index, :new, :create]
  end

  resources :releases, only: [:show, :edit, :update, :destroy]

  get "dashboard", to: "pages#dashboard"

  get "results", to: "pages#results"

  get "test", to: "testsrequests#receiving"
  # post "results", to: "pages#save_btn", as: :save_result
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :releases
  
end

app/models/release.rb
class Release < ApplicationRecord
  belongs_to :list
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @releases = Release.all
  end

  def results
    @search_query = params['search']['title']
    @release = discogs_api(@search_query)
    @cover_image = discogs_api_img(@search_query)
    @list = List.find_by(title: 'spotlight')
    new_api_release = Release.new(
      artist: @release.artists[0].name,
      title: @release.title,
      label: @release.labels.first.name,
      catalog_number: @release.labels.first.catno,
      format: @release.formats.first.name,
      released: @release.released,
      styles: @release.styles,
      tracklist: @release.tracklist.map { |track| track.title },
      cover_url: @cover_image
    )
    list = List.find_by(title: 'spotlight')
    new_api_release.list = list
    new_api_release.save

    # redirect_to test_path(random_hash: "Test")
    # redirect_to save_result_path(passed_parameter: "Test")
  end

  # def save_btn
  #   @test_value = params[:passed_parameter]
    # call_from_api = results
    # new_api_release = Release.new(
    #   artist: @release.artists[0].name,
    #   title: @release.title,
    #   label: @release.labels.first.name,
    #   catalog_number: @release.labels.first.catno,
    #   format: @release.formats.first.name,
    #   released: @release.released,
    #   styles: @release.styles,
    #   tracklist: @release.tracklist.map { |track| track.title },
    #   cover_url: @cover_image
    # )
    # list = List.find_by(title: 'spotlight')
    # new_api_release.list = list
    # new_api_release.save
  #   raise
  # end

  # def create
  #   @api_release = Release.new(
  #     artist: @release.artists[0].name,
  #     title: @release.title,
  #     label: @release.labels.first.name,
  #     catalog_number: @release.labels.first.catno,
  #     format: @release.formats.first.name,
  #     released: @release.released,
  #     styles: @release.styles,
  #     tracklist: @release.tracklist.map { |track| track.title },
  #     cover_url: @cover_image
  #   )
  #   @list = List.find_by(title: 'spotlight')
  #   @api_release.list = @list
  #   # response_from_api = discogsApi()
  #   @api_release.save

  #   redirect_to dashboard_path
  # end

  private

  def discogs_api(search_input)
    wrapper = Discogs::Wrapper.new('DigDeeper')
    auth_wrapper = Discogs::Wrapper.new('DigDeeper', user_token: 'woLJMkIArTDEQgXUMPAAuNacoDrNRjoZRUVoVZLU')

    search = auth_wrapper.search(search_input, :per_page => 1)
    release_id = search.results.first.id.to_s
    wrapper.get_release(release_id)
  end

  def discogs_api_img(search_input)
    wrapper = Discogs::Wrapper.new('DigDeeper')
    auth_wrapper = Discogs::Wrapper.new('DigDeeper', user_token: 'woLJMkIArTDEQgXUMPAAuNacoDrNRjoZRUVoVZLU')

    search = auth_wrapper.search(search_input, :per_page => 1)
    search.results.first.cover_image
  end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  def index
    @releases = Release.where(list_id: params[:list_id])
  end

  def show
    @release = Release.find(params[:id])
  end

  def new
    @release = Release.new
    @list = List.find(params[:list_id])
  end

  def create
    @release = Release.new(release_params)
    @list = List.find(params[:list_id])
    @release.list = @list
    # response_from_api = discogsApi()
    @release.save

    redirect_to release_path(@release)
  end

  def edit
    @release = Release.find(params[:id])
  end

  def update
    @release = Release.find(params[:id])
    @release.update(release_params)
    redirect_to release_path(@release)
  end

  private

  def release_params
    params.require(:release).permit(:artist, :title, :label, :catalog_number, :format, :released, :styles, :tracklist, :link, :cover_url, :photo)
  end
end

app/controllers/testsrequests_controller.rb
class TestsrequestsController < ApplicationController
  def receiving
    @received_data = params[:random_hash]
    raise
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/testsrequests_helper.rb
module TestsrequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigDeeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">

  <h1>Dashboard</h1>

  <div class="search-form">
    <%= simple_form_for :search, url: results_path, method: "GET", html: { class: 'form-inline' } do |f| %>
      <%= f.input :title, input_html: {value: ""} %>
      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
<div class = "sportlight_card">
<img src='' alt="" class="cover_img">
  <h6 class = "left">cover</h6>
  <h6 class = "right">Artist</h6>
  <h6>TITle</h6>
  <h6>LABEL</h6>
  <h6>RELEASED</h6>
  <h6>TAGS</h6>
</div>
  <% @releases.each do |release| %>
    <div class = "sportlight_card">
    <img src='<%= release.cover_url  %>' alt="" class="cover_img">
      <h6> <%= release.artist %></h6>
      <h6> <%= release.title %> </h6>
      <h6> <%= release.label %> </h6>
      <h6> <%= release.released %> </h6>
      <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Dropdown button
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
</div>
    </div>


  <% end %>

</div>

app/views/pages/home.html.erb
<h1>Home Page</h1>

app/views/pages/results.html.erb
<div class="container mb-5">

  <%= link_to "Back to Dashboard", :back, class: "btn btn-primary my-3" %>

  <div class="d-flex justify-content-center m-3">
    <h1>Here is what we found:</h1>
  </div>

  <div class="results-cover-info">
    <div class="m-3">
      <img src="<%= @cover_image %>" alt="release image">
    </div>

    <div>
      <div class="m-3">
        <h2><%= @release.artists[0].name %> - <%= @release.title %></h2>
        <p>Label: <%= @release.labels.first.name %> - <%= @release.labels.first.catno %></p>
        <p>Format: <%= @release.formats.first.name %> - <%= @release.formats.first.descriptions %></p>
        <p> Released: <%= @release.released %></p>
        <p>Styles: <%= @release.styles %></p>
      </div>

      <div class="m-3">
        <p><strong>Tracklist:</strong></p>
        <% @release.tracklist.each_with_index do |track, index| %>
            <small><%= index + 1 %>. <%= track.title %></small>
            <br>
        <% end %>
      </div>

      <%= link_to "Save to Spotlight List", dashboard_path, class: "btn btn-primary my-3" %>
    </div>

  </div>



</div>

app/views/releases/edit.html.erb
<div class="container">

<%= link_to "Back to the list", :back, class: "btn_main" %>
 <%= simple_form_for [@list, @release] do |f| %>
   <%= f.input :artist %>
   <%= f.input :title %>
   <%= f.input :label %>
   <%= f.input :catalog_number %>
   <%= f.input :format %>
   <%= f.input :released %>
   <%= f.input :styles %>
   <%= f.input :tracklist %>
   <%= f.input :link %>
   <%= f.input :cover_url %>
   <%= f.input :comment %>
   <%= f.input :photo, as: :file %>
   <%= f.submit %>
 <% end %>
</div>

app/views/releases/index.html.erb
<%= link_to "Create a new release", new_list_release_path, class: "button_main my-3" %>

<div class="container">
 <% @releases.each do |release| %>
   <%= release.artist %>
  <%# <%= release.title %> 
 <% end  %>


</div>

app/views/releases/new.html.erb
<div class="container">
 <%= simple_form_for [@list, @release] do |f| %>
   <%= f.input :artist %>
   <%= f.input :title %>
   <%= f.input :label %>
   <%= f.input :catalog_number %>
   <%= f.input :format %>
   <%= f.input :released %>
   <%= f.input :styles %>
   <%= f.input :tracklist %>
   <%= f.input :link %>
   <%= f.input :cover_url %>
   <%= f.input :comment %>
   <%= f.input :photo, as: :file %>
   <%= f.submit %>
   <% end %>
 </div>

app/views/releases/show.html.erb
<div class="content-container">
<%= link_to "Edit this release", edit_release_path(@release), class: "btn_main" %>
<img class="release-img, url('<%= cl_image_path @release.cover_url %>')">
  <h2><%= @release.title %></h2> %>
    <p><%= @release.label %></p>
    <p><%= @release.catalog_number %></p>
    <p><%= @release.format %></p>
    <p><%= @release.released %></p>
    <p><%= @release.styles %></p>
    <p><%= @release.tracklist %></p>
</div>

<div class="background-blur-img"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @release.cover_url %>')">

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>